<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="beeLang"
    nsURI="http://www.eclipse.org/b3/BeeLang" nsPrefix="beeLang">
  <eClassifiers xsi:type="ecore:EClass" name="BeeModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//IType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//B3Function"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concern" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//BConcern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertySets" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//BPropertySet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//BuildUnit"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionMode" eType="ecore:EEnum platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//ExecutionMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType platform:/resource/org.eclipse.b3.build/model/B3Build.ecore#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implements" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultProperties" eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//BPropertySet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedCapabilities" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.b3.build/model/B3Build.ecore#//VersionedCapability"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredCapabilities" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.b3.build/model/B3Build.ecore#//RequiredCapability"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaRequiredCapabilities"
        upperBound="-1" eType="ecore:EClass platform:/resource/org.eclipse.b3.build/model/B3Build.ecore#//RequiredCapability"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concerns" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//BConcern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="synchronizations" upperBound="-1"
        eType="#//Synchronization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="builders" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.b3.build/model/B3Build.ecore#//Builder"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//B3Function"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositoryConfigurations"
        upperBound="-1" eType="#//RepositoryConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertySets" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//BPropertySet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//ContainerConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetPropertyOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//BExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnsetPropertyOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Synchronization">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partrefs" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDeclarationList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="BuilderOutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass platform:/resource/org.eclipse.b3.build/model/B3Build.ecore#//PathGroup"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryConfiguration"/>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryDeclaration" eSuperTypes="#//RepositoryConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//IType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//BExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResolutionStrategy" eSuperTypes="#//RepositoryConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strategy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositoryConfig" upperBound="-1"
        eType="#//RepositoryConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//IType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextBlock" eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//BExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarargParameterDeclaration" eSuperTypes="#//ParameterDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/resource/org.eclipse.b3.backend/model/B3Backend.ecore#//IType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
