/*
 * Copied from "generated by Xtext" version
 */

package org.eclipse.b3.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * 
 */
public class BeeLangUiExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipse.b3.ui.internal.BeeLangUiActivator.getInstance().getBundle();
	}

	@Override
	protected Injector getInjector() {
		return org.eclipse.b3.ui.internal.BeeLangUiActivator.getInstance().getInjector("org.eclipse.b3.BeeLang");
	}

}
