/*
 * generated by Xtext
 */
package org.eclipse.b3.ui;

import org.eclipse.b3.beelang.ui.templates.B3TemplateStore;
import org.eclipse.b3.beelang.ui.xtext.linked.ExtLinkedXtextEditor;
import org.eclipse.b3.ui.coloring.BeeLangHighlightConfiguration;
import org.eclipse.b3.ui.coloring.BeeLangSemanticHighlightingCalculator;
import org.eclipse.b3.ui.coloring.BeeLangTokenToAttributeIdMapper;
import org.eclipse.b3.ui.contentassist.BeeLangAutoEditStrategy;
import org.eclipse.b3.ui.outline.BeeLangOutlineNodeAdapterFactory;
import org.eclipse.jface.text.templates.persistence.TemplateStore;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;
import org.eclipse.xtext.ui.editor.XtextEditor;
import org.eclipse.xtext.ui.editor.outline.actions.IContentOutlineNodeAdapterFactory;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.antlr.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.validation.ValidatingEditorCallback;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BeeLangUiModule extends org.eclipse.b3.ui.AbstractBeeLangUiModule {
	public BeeLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends org.eclipse.jface.text.IAutoEditStrategy> bindIAutoEditStrategy() {
		return BeeLangAutoEditStrategy.class;
	}

	// To get nodes in outline view adapted for the purpose of attaching menus
	@Override
	public Class<? extends IContentOutlineNodeAdapterFactory> bindIContentOutlineNodeAdapterFactory() {
		return BeeLangOutlineNodeAdapterFactory.class;
	}

	public Class<? extends IHighlightingConfiguration> bindILexicalHighlightingConfiguration() {
		return BeeLangHighlightConfiguration.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return BeeLangSemanticHighlightingCalculator.class;
	}

	@Override
	public Class<? extends IXtextEditorCallback> bindIXtextEditorCallback() {
		return ValidatingEditorCallback.class;
	}

	@Override
	public Class<? extends TemplateStore> bindTemplateStore() {
		return B3TemplateStore.class;
	}

	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindTokenToAttributeIdMapper() {
		return BeeLangTokenToAttributeIdMapper.class;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.eclipse.xtext.ui.DefaultUiModule#configure(com.google.inject.Binder)
	 */
	@Override
	public void configure(Binder binder) {
		// binder.bind(XtextDocumentProvider.class).to(EFSExtendedDocumentProvider.class);
		binder.bind(XtextEditor.class).to(ExtLinkedXtextEditor.class);
		super.configure(binder);
	}
}
