/*
 * generated by Xtext
 */
package org.eclipse.b3.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class BeeLangTransformer extends AbstractDeclarativeSemanticModelTransformer {

}
